### ISSUE TITLE
task list LR

### ISSUE THREAD

**Issue by louisnfr** [louisnfr/minishell#2]
- [x] divide minishell.h into severals files
- [x] create parsing summary doc
- [x] restructure project
- [x] edit functions args to avoid too many `->` with structures
- [x] crop prompt when too many subdirectories `~/Desktop/1/2/3/4`
- [x] get libft.c functions into libft/
- [x] simplify `ft_split_on_first()`
- [x] fix leaks
- [x] protect mallocs
- [x] norm
