### ISSUE TITLE
task list EF

### ISSUE THREAD

**Issue by EugenieF** [louisnfr/minishell#7]
- [x] error msg "bash: ./: is a directory"
- [x] error msg "bash: .:  filename arguments required
                           .: usage: . filename [arguments]"
- [x] return value errors
- [x] Split args : <  <<   >  >>  ( )  [ ]  { }   " "   '  '
- [x] Multi pipe
- [x] Heredoc
- [x] Management files
- [x] tester.sh
- [x] leaks
- [x] norm
